const variables = {
         "fonts": [
"@import url('https://fonts.googleapis.com/css2?family=Spartan:wght@300&display=swap')",
"@import url('https://fonts.googleapis.com/css2?family=Fira+Sans:wght@800&display=swap')"
],
   "primaryfontFamily1": "jose",
   "primaryfontFamily2": "Spartan",
   "primaryfontFamily3": "Spartan",
   "primaryfontFamily4": "Spartan",
   "primaryfontFamily5": "Spartan",
   "secundaryfontFamily1": "Spartan",
   "secundaryfontFamily2": "Spartan",
   "secundaryfontFamily3": "Spartan",
   "secundaryfontFamily4": "Spartan",
   "secundaryfontFamily5": "Spartan",
   "primary-color1": "#666569",
   "color-icon": "#8b8b8b",
   "dark-grey": "#929292",
   "ligth-grey": "#c8c7c7",
   "color-white": "white",
   "color-red": "#de5246",
   "background-colorBody": "#e9eaea",
   "button-background-color_-0": "#0d6efd",
   "button-background-color_-1": "#2f80ed",
   "button-background-color_-2": "black",
   "button-background-color_-3": "black",
   "button-background-color_-4": "black",
   "button-background-color_-5": "black",
   "button-color_-c1": "black",
   "button-color_-c2": "black",
   "button-color_-c3": "black",
   "button-color_-c4": "black",
   "button-color_-c5": "black",
   "size-s_-1": "1vw",
   "size-s_-2": "1vw",
   "size-s_-3": "1vw",
   "size-s_-4": "1vw",
   "size-s_-5": "1vw",
   "background-color1": "#e9eaea",
   "background-color2": "#e9eaea",
   "card-outline-width": "0px",
   "container": "0 9% 0 9%",
};
  
module.exports = variables;
  